/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'anatolii' at '10/5/14 9:49 PM' with Gradle 2.0
 *
 * @author anatolii, @date 10/5/14 9:49 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
